"""
QQ Bot service layer — bridges QQ message handling with ChatService.
Mirrors app/telegram/service.py but adapted for OneBot/NapCat.
"""
from __future__ import annotations

import asyncio
import json as _json
import logging
import random
from datetime import datetime, timedelta, timezone
from typing import Any, Callable

from app.cot_broadcaster import publish_messages_updated
from app.database import SessionLocal
from app.models.models import Message, Settings

_TZ_EAST8 = timezone(timedelta(hours=8))
from app.telegram.service import (
    encode_photo_base64,
    get_buffer_seconds,
    get_chat_mode,
    get_session_info,
)

from . import napcat_api

logger = logging.getLogger(__name__)

# Sources that should not be re-sent by channel handlers (they have their own delivery)
_EXCLUDE_SOURCES = {"proactive", "cafe", "reflection"}


# ── Chat completion (QQ version) ─────────────────────────────────────────────

def _chat_completion_sync(
    session_id: int,
    assistant_name: str,
    message: str,
    short_mode: bool,
    assistant_id: int | None = None,
    qq_message_ids: list[int] | None = None,
    on_intermediate: Callable[[str, int], None] | None = None,
) -> list[dict[str, Any]]:
    from sqlalchemy import func
    from app.routers.chat import _load_session_messages
    from app.services.chat_service import ChatService
    from app.services.generation_coordinator import GenerationLock

    db = SessionLocal()
    try:
        # Serialize with other channel handlers (cafe/qq_group/tg) so triggers
        # from different sources don't collide into one merged user payload.
        with GenerationLock("qq") as _gen_lock:
            # User messages are now stored immediately in _handle_text / _handle_voice
            # (so UI sees them before buffer fires). Just remember the current max id
            # to filter assistant messages generated by this chat round.
            max_id_before = (
                db.query(func.max(Message.id))
                .filter(Message.session_id == session_id)
                .scalar()
            ) or 0

            chat_service = ChatService(db, assistant_name, assistant_id=assistant_id, source="qq")
            # Enable TTS emotion if master switch is on
            _voice_on = db.query(Settings).filter(Settings.key == "proactive_voice_enabled").first()
            if _voice_on and _voice_on.value == "true":
                _tts_key = db.query(Settings).filter(Settings.key == "tts_api_key").first()
                if _tts_key and _tts_key.value:
                    chat_service.tts_emotion_enabled = True

            messages = _load_session_messages(db, session_id)
            sent_db_ids: set[int] = set()
            for event_str in chat_service.stream_chat_completion(
                session_id, messages, short_mode=short_mode, source="qq",
            ):
                # Detect intermediate message events and send immediately
                if on_intermediate and event_str.startswith("data: "):
                    try:
                        data = _json.loads(event_str[6:].strip())
                        if isinstance(data, dict) and "intermediate" in data:
                            im = data["intermediate"]
                            if not getattr(chat_service, "_switched_channel", None):
                                on_intermediate(im["content"], im["db_id"])
                                sent_db_ids.add(im["db_id"])
                    except (ValueError, KeyError, TypeError):
                        pass

            # Stream ended — assistant message already persisted. Release the global
            # generation lock now so the next queued source (another channel) can start,
            # while we finish up the local DB query + result building + platform send.
            _gen_lock.release()

            new_msgs = (
                db.query(Message)
                .filter(
                    Message.session_id == session_id,
                    Message.id > max_id_before,
                    Message.role == "assistant",
                    Message.content != "",
                )
                .order_by(Message.id)
                .all()
            )
            result = [
                {"role": "assistant", "content": m.content, "db_id": m.id}
                for m in new_msgs
                if not (m.meta_info or {}).get("no_message")
                and m.id not in sent_db_ids
                and (m.meta_info or {}).get("source") not in _EXCLUDE_SOURCES
            ]
            switched = getattr(chat_service, "_switched_channel", None)
            if switched:
                for r in result:
                    r["_switched_channel"] = switched
        return result
    finally:
        db.close()


async def call_chat_completion(
    session_id: int,
    assistant_name: str,
    message: str,
    short_mode: bool,
    assistant_id: int | None = None,
    qq_message_ids: list[int] | None = None,
    user_id: int | None = None,
) -> list[dict[str, Any]]:
    on_intermediate = None
    if user_id:
        loop = asyncio.get_running_loop()
        def _on_intermediate(content: str, db_id: int) -> None:
            fut = asyncio.run_coroutine_threadsafe(
                send_reply_with_voice(user_id, content), loop,
            )
            try:
                fut.result(timeout=60)
            except Exception:
                logger.warning("[qq] Failed to send intermediate message db_id=%d", db_id)
        on_intermediate = _on_intermediate
    return await asyncio.to_thread(
        _chat_completion_sync, session_id, assistant_name, message, short_mode,
        assistant_id, qq_message_ids, on_intermediate,
    )


# ── Chat completion with image ───────────────────────────────────────────────

def _chat_completion_with_image_sync(
    session_id: int,
    assistant_name: str,
    message: str,
    image_data: str | None = None,
    short_mode: bool = False,
    assistant_id: int | None = None,
    on_intermediate: Callable[[str, int], None] | None = None,
) -> list[dict[str, Any]]:
    from app.routers.chat import _load_session_messages
    from app.services.chat_service import ChatService

    db = SessionLocal()
    try:
        user_msg = Message(
            session_id=session_id,
            role="user",
            content=message,
            meta_info={"source": "qq"},
            image_data=image_data,
        )
        db.add(user_msg)
        db.commit()
        db.refresh(user_msg)
        publish_messages_updated(session_id, user_msg.id)
        from app.services.proactive_service import touch_last_user_message_at
        touch_last_user_message_at(db)
        max_id_before = user_msg.id

        chat_service = ChatService(db, assistant_name, assistant_id=assistant_id, source="qq")
        messages = _load_session_messages(db, session_id)
        sent_db_ids: set[int] = set()
        for event_str in chat_service.stream_chat_completion(
            session_id, messages, short_mode=short_mode, source="qq",
        ):
            if on_intermediate and event_str.startswith("data: "):
                try:
                    data = _json.loads(event_str[6:].strip())
                    if isinstance(data, dict) and "intermediate" in data:
                        im = data["intermediate"]
                        if not getattr(chat_service, "_switched_channel", None):
                            on_intermediate(im["content"], im["db_id"])
                            sent_db_ids.add(im["db_id"])
                except (ValueError, KeyError, TypeError):
                    pass

        new_msgs = (
            db.query(Message)
            .filter(
                Message.session_id == session_id,
                Message.id > max_id_before,
                Message.role == "assistant",
                Message.content != "",
            )
            .order_by(Message.id)
            .all()
        )
        result = [
            {"role": "assistant", "content": m.content, "db_id": m.id}
            for m in new_msgs
            if not (m.meta_info or {}).get("no_message")
            and m.id not in sent_db_ids
            and (m.meta_info or {}).get("source") not in _EXCLUDE_SOURCES
        ]
        switched = getattr(chat_service, "_switched_channel", None)
        if switched:
            for r in result:
                r["_switched_channel"] = switched
        return result
    finally:
        db.close()


async def call_chat_completion_with_image(
    session_id: int,
    assistant_name: str,
    message: str,
    image_data: str | None = None,
    short_mode: bool = False,
    assistant_id: int | None = None,
    user_id: int | None = None,
) -> list[dict[str, Any]]:
    on_intermediate = None
    if user_id:
        loop = asyncio.get_running_loop()
        def _on_intermediate(content: str, db_id: int) -> None:
            fut = asyncio.run_coroutine_threadsafe(
                send_reply_with_voice(user_id, content), loop,
            )
            try:
                fut.result(timeout=60)
            except Exception:
                logger.warning("[qq] Failed to send intermediate message db_id=%d", db_id)
        on_intermediate = _on_intermediate
    return await asyncio.to_thread(
        _chat_completion_with_image_sync,
        session_id, assistant_name, message, image_data, short_mode, assistant_id,
        on_intermediate,
    )


# ── Store message only (no chat completion) ──────────────────────────────────

def _store_message_only_sync(
    session_id: int,
    content: str,
    image_data: str | None = None,
    qq_message_id: list[int] | None = None,
) -> int:
    db = SessionLocal()
    try:
        msg = Message(
            session_id=session_id,
            role="user",
            content=content,
            meta_info={"source": "qq"},
            image_data=image_data,
            qq_message_id=qq_message_id,
        )
        db.add(msg)
        db.commit()
        db.refresh(msg)
        publish_messages_updated(session_id, msg.id)
        return msg.id
    finally:
        db.close()


async def store_message_only(
    session_id: int,
    content: str,
    image_data: str | None = None,
    qq_message_id: list[int] | None = None,
) -> int:
    return await asyncio.to_thread(_store_message_only_sync, session_id, content, image_data, qq_message_id)


# ── QQ message ID lookup / update ────────────────────────────────────────────

def _lookup_by_qq_id_sync(qq_msg_id: int) -> dict[str, Any] | None:
    from sqlalchemy import cast
    from sqlalchemy.dialects.postgresql import JSONB as JSONB_TYPE

    db = SessionLocal()
    try:
        msg = (
            db.query(Message)
            .filter(Message.qq_message_id.op("@>")(cast([qq_msg_id], JSONB_TYPE)))
            .first()
        )
        if msg:
            return {"id": msg.id, "content": msg.content, "role": msg.role}
        return None
    finally:
        db.close()


async def lookup_by_qq_message_id(qq_msg_id: int) -> dict[str, Any] | None:
    return await asyncio.to_thread(_lookup_by_qq_id_sync, qq_msg_id)


def _update_qq_msg_id_sync(message_db_id: int, qq_msg_id: int) -> None:
    db = SessionLocal()
    try:
        msg = db.get(Message, message_db_id)
        if msg:
            msg.qq_message_id = [qq_msg_id]
            db.commit()
    finally:
        db.close()


async def update_qq_message_id(message_db_id: int, qq_msg_id: int) -> None:
    return await asyncio.to_thread(_update_qq_msg_id_sync, message_db_id, qq_msg_id)


# ── Send reply with optional TTS voice ───────────────────────────────────────

def _typing_delay(text: str) -> float:
    """Simulate natural typing delay based on message length."""
    base = random.uniform(2.0, 3.0)
    length_bonus = min(len(text) * 0.05, 2.5)
    return base + length_bonus


async def _send_one_part(user_id: int, text: str, *, explicit_block: bool = False) -> int | None:
    """Send a single part, handling [[voice:EMOTION]] tags. Returns last sent qq message_id."""
    from app.services.tts_service import EMOTION_TAG_RE, VALID_EMOTIONS, synthesize

    segments = EMOTION_TAG_RE.split(text)
    last_msg_id: int | None = None

    # No voice tag → plain text
    if len(segments) == 1:
        clean = text.strip()
        if clean:
            last_msg_id = await napcat_api.send_private_msg(user_id, clean)
        return last_msg_id

    sent_something = False
    for idx in range(0, len(segments), 2):
        seg_text = segments[idx].strip()
        if not seg_text:
            continue

        if sent_something:
            await asyncio.sleep(_typing_delay(seg_text))

        if idx == 0:
            # Text before the first voice tag
            last_msg_id = await napcat_api.send_private_msg(user_id, seg_text)
            sent_something = True
        else:
            from app.services.tts_service import resolve_emotion
            emotion = resolve_emotion(segments[idx - 1])

            if explicit_block:
                voice_line = seg_text
                rest_text = ""
            else:
                lines = seg_text.split("\n", 1)
                voice_line = lines[0].strip()
                rest_text = lines[1].strip() if len(lines) > 1 else ""

            voice_sent = False
            if voice_line and emotion and len(voice_line) <= 300:
                try:
                    audio_bytes = await asyncio.to_thread(synthesize, voice_line, emotion)
                    if audio_bytes:
                        await napcat_api.send_private_voice(user_id, audio_bytes)
                        voice_sent = True
                        logger.info("[qq voice] Sent voice (emotion=%s, %d chars)", emotion, len(voice_line))
                except Exception as e:
                    logger.warning("[qq voice] Voice send failed: %s", e)

            if voice_line and not voice_sent:
                last_msg_id = await napcat_api.send_private_msg(user_id, voice_line)
                sent_something = True
            elif voice_sent:
                sent_something = True

            if rest_text:
                if sent_something:
                    await asyncio.sleep(_typing_delay(rest_text))
                last_msg_id = await napcat_api.send_private_msg(user_id, rest_text)
                sent_something = True

    return last_msg_id


async def send_reply_with_voice(user_id: int, text: str) -> int | None:
    """Send reply, splitting by [NEXT] / blank lines. Each part is sent as a separate QQ message.
    Returns the last sent qq message_id (for mapping back to DB)."""
    if not text.strip():
        return None

    # Safety net: strip any leaked memory reference IDs, metadata, or THINK blocks
    import re
    text = re.sub(r'(?:\[THINK\]|<scratchpad>).*?(?:\[/THINK\]|</THINK>|</thinking>|</scratchpad>)', '', text, flags=re.DOTALL)
    for _orphan in ('<scratchpad>', '</scratchpad>', '[THINK]', '[/THINK]', '</THINK>', '</thinking>'):
        text = text.replace(_orphan, '')
    text = re.sub(r'\[#\s*\d+\s*\]\s*', '', text)
    text = re.sub(r'\[\[used:[\d,\s]+\]\]', '', text)
    text = re.sub(r'\(来源:\s*\w+\)\s*$', '', text, flags=re.MULTILINE)
    text = re.sub(r'\[?VIA[:\uff1a](telegram|qq|wechat)\]?', '', text, flags=re.IGNORECASE)
    # [NEXT] and empty lines split into separate messages; single newlines preserved
    text = text.replace("[NEXT]", "\n\n")
    parts = [p.strip() for p in re.split(r'\n\s*\n', text) if p.strip()]
    has_next = len(parts) > 1
    last_msg_id: int | None = None

    for i, part in enumerate(parts):
        if i > 0:
            await asyncio.sleep(_typing_delay(part))
        mid = await _send_one_part(user_id, part, explicit_block=has_next)
        if mid is not None:
            last_msg_id = mid

    return last_msg_id
